baseURL = 'https://zyjeski.netlify.app/'
languageCode = 'en-us'
title = 'Jeffrey A. Zyjeski, Esq.'
theme = "AUTHOR"

# Basic author information
[params]
  author = 'Jeffrey A. Zyjeski'
  description = 'Speculative fiction author'

# Optional social media links
[params.social]
  twitter = '@zekusmaximus'
  facebook = 'facebook.com/zyjeski'
  instagram = '/zeksumaximus'
  # goodreads = 'yourgoodreadsprofile'
  amazon = 'youramazonauthorpage'

# Menu configuration (from your existing theme)
[[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menu.main]]
    name = 'Books'
    pageRef = '/books'
    weight = 20

  [[menu.main]]
    name = 'Stories'
    pageRef = '/stories'
    weight = 30

  [[menu.main]]
    name = 'Audio'
    pageRef = '/audio'
    weight = 40

  [[menu.main]]
    name = 'Blog'
    pageRef = '/posts'
    weight = 50
    
  [[menu.main]]
    name = 'Newsletter'
    pageRef = '/newsletter'
    weight = 60

  [[menu.main]]
    name = 'About'
    pageRef = '/about'
    weight = 70