baseURL = 'https://zyjeski.netlify.app/'
languageCode = 'en-us'
title = 'Jeffrey A. Zyjeski, Esq.'
theme = "AUTHOR"

# Basic author information
[params]
  author = 'Jeffrey A. Zyjeski'
  description = 'Speculative fiction author'

# Optional social media links
[params.social]
  twitter = '@zekusmaximus'
  facebook = 'facebook.com/zyjeski'
  instagram = '/zeksumaximus'
  # goodreads = 'yourgoodreadsprofile'
  # amazon = 'youramazonauthorpage'

# Menu configuration (from your existing theme)
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Books'
pageRef = '/books'
weight = 20

[[menus.main]]
name = 'Stories'
pageRef = '/stories'
weight = 30

[[menus.main]]
name = 'Blog'
pageRef = '/posts'
weight = 40

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 50