baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[[menus.main]]
name = 'The Protocol'
pageRef = '/books'
weight = 10

[[menus.main]]
name = 'Koans'
pageRef = '/stories'
weight = 20

[[menus.main]]
name = 'Simulations'
pageRef = '/audio'
weight = 30

[[menus.main]]
name = 'Dharma Log'
pageRef = '/posts'
weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
