baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

# Add to themes/AUTHOR/hugo.toml or hugo.toml in the root directory

[menu]
  [[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menu.main]]
    name = 'The Protocol'
    pageRef = '/books'
    weight = 20

  [[menu.main]]
    name = 'Koans'
    pageRef = '/stories'
    weight = 30

  [[menu.main]]
    name = 'Simulations'
    pageRef = '/audio'
    weight = 40

  [[menu.main]]
    name = 'Dharma Log'
    pageRef = '/posts'
    weight = 50

  [[menu.main]]
    name = 'About'
    pageRef = '/about'
    weight = 60